# Generated by Django 6.0.2 on 2026-02-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('full_description', models.TextField(blank=True, help_text='Detailed explanation of the service.')),
                ('features_list', models.TextField(help_text='Enter the bullet points from the brochure here, separated by commas or new lines.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True, help_text='Short introduction or quote.')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('location', models.CharField(blank=True, help_text='e.g. Dubai Hills', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of work done.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(help_text='Select which service category this project belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='growscape_app.service')),
            ],
        ),
    ]
