# Generated by Django 6.0.2 on 2026-02-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growscape_app', '0002_blog_category_contactmessage_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('contacted', 'Contacted'), ('site_visit', 'Site Visit Scheduled'), ('closed', 'Closed')], default='new', max_length=20)),
                ('preferred_date', models.DateField(blank=True, help_text='Preferred date for site visit', null=True)),
                ('location', models.CharField(blank=True, help_text='Villa/Property Location', max_length=200)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='growscape_app.service')),
            ],
            options={
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
