# Generated by Django 6.0.2 on 2026-02-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growscape_app', '0003_serviceinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinquiry',
            name='status',
        ),
    ]
